-- Code generated by protoc-gen-labset (mode=go-sqlc-atlas). DO NOT EDIT.
-- source: projectmanagement/v1

-- name: CreateProject :one
INSERT INTO projectmanagement_v1.project (id, name, description)
VALUES (sqlc.arg('id'), sqlc.arg('name'), sqlc.arg('description'))
RETURNING id, name, description, created_at, updated_at, deleted_at;

-- name: GetProject :one
SELECT id, name, description, created_at, updated_at, deleted_at FROM projectmanagement_v1.project
WHERE id = sqlc.arg('id') AND deleted_at IS NULL;

-- name: UpdateProject :one
UPDATE projectmanagement_v1.project
SET name = COALESCE(sqlc.narg('name'), name), description = COALESCE(sqlc.narg('description'), description), updated_at = now()
WHERE id = sqlc.arg('id') AND deleted_at IS NULL
RETURNING id, name, description, created_at, updated_at, deleted_at;

-- name: DeleteProject :exec
UPDATE projectmanagement_v1.project
SET deleted_at = now()
WHERE id = sqlc.arg('id') AND deleted_at IS NULL;

-- name: ListProject :many
SELECT id, name, description, created_at, updated_at, deleted_at FROM projectmanagement_v1.project
WHERE deleted_at IS NULL
ORDER BY created_at ASC;
