-- Code generated by protoc-gen-labset (mode=go-sqlc-atlas). DO NOT EDIT.
-- source: projectmanagement/v1

-- name: CreateProject :one
INSERT INTO project (id, name, description)
VALUES ($1, $2, $3)
RETURNING *;

-- name: GetProject :one
SELECT * FROM project
WHERE id = $1 AND deleted_at IS NULL;

-- name: UpdateProject :one
UPDATE project
SET name = $2, description = $3, updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING *;

-- name: DeleteProject :exec
UPDATE project
SET deleted_at = now()
WHERE id = $1 AND deleted_at IS NULL;

-- name: ListProject :many
SELECT * FROM project
WHERE deleted_at IS NULL
ORDER BY created_at;

-- name: CreateTask :one
INSERT INTO task (id, project_id, title, priority)
VALUES ($1, $2, $3, $4)
RETURNING *;

-- name: GetTask :one
SELECT * FROM task
WHERE id = $1 AND deleted_at IS NULL;

-- name: ListTask :many
SELECT * FROM task
WHERE deleted_at IS NULL
ORDER BY created_at;
