-- Code generated by protoc-gen-labset (mode=go-sqlc-atlas). DO NOT EDIT.
-- source: projectmanagement/v1

CREATE SCHEMA IF NOT EXISTS projectmanagement_v1;

CREATE TABLE projectmanagement_v1.project (
  id uuid PRIMARY KEY,
  name text NOT NULL,
  description text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz
);

CREATE TABLE projectmanagement_v1.task (
  id uuid PRIMARY KEY,
  project_id text NOT NULL,
  title text NOT NULL,
  priority bigint,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz
);
