# Code generated by protoc-gen-labset (mode=go-sqlc-atlas). DO NOT EDIT.
env "local" {
  src = "file://sql/schema.sql"
  url = getenv("DATABASE_URL")
  dev = "docker://postgres/16/dev?search_path=public"
  migration {
    dir = "file://sql/migrations?format=goose"
  }
}
