version: "2"

formatters:
  enable:
    - gofmt
    - goimports
    - golines

linters:
  enable:
    - depguard
    - govet
    - protogetter
    - staticcheck
  settings:
    depguard:
      rules:
        main:
          allow:
            - $gostd
            - buf.build/go/bufplugin/check
            - github.com/labset/protobuf-toolchain/
            - github.com/stretchr/testify
            - google.golang.org/protobuf