[tasks."toolchain:tidy"]
run = "go mod tidy"

[tasks."toolchain:generate"]
run = "go generate ./..."

[tasks."toolchain:lint"]
run = "golangci-lint run"

[tasks."toolchain:lint:fix"]
run = [
    "golangci-lint run --fix",
    "golangci-lint fmt"
]

[tasks."toolchain:format"]
run = "golangci-lint fmt"

[tasks."toolchain:test"]
run = "go test ./..."

[tasks."toolchain:build"]
run = "goreleaser build --clean --snapshot"