[tasks.clean]
description = "clean it"
run = "rm -rf dist"

[tasks.tidy]
description = "tidy it"
depends = ["schema:tidy", "toolchain:tidy"]

[tasks.generate]
description = "generate it"
depends = ["schema:generate", "toolchain:generate"]

[tasks.lint]
description = "lint it"
depends = ["schema:lint", "toolchain:lint"]

[tasks.test]
description = "test it"
depends = ["toolchain:test"]

[tasks.build]
description = "build it"
depends = ["toolchain:build"]